<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>DocumentQuickstart</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Marten" />
        <PackageReference Include="Spectre.Console" />
    </ItemGroup>

</Project>
